apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: development
spec:
    containers:
    - image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
      command:
          - sleep
          - "3600"
      name: busybox
