apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 2
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      volumes:
      - name: "persistent-storage"
        hostPath:
          path: "/data"
      containers:
      - name: master
        image: "registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/kubeguide-redis-master:latest"
        ports:
        - containerPort: 6379
