apiVersion: v1
kind: Pod
metadata:
    name: redis-slave
    labels:
        name: redis-slave
spec:
    containers:
    - name: slave
      image: "registry.cn-hangzhou.aliyuncs.com/kubeguide/guestbook-redis-slave:latest"
      env:
      - name: GET_HOSTS_FROM
        value: env
      ports:
      - containerPort: 6379
