apiVersion: v1
kind: Pod
metadata:
    name: hello-world
spec: # specification of the pod's contents
    restartPolicy: Never
    containers:
    - name: hello
      image: "hub.c.163.com/public/ubuntu:16.04 "
      command: ["/bin/echo","hello","world"]
