apiVersion: v1
kind: ReplicationController
metadata:
    name: frontend
    labels:
        name: frontend
spec:
    replicas: 3
    selector:
        name: frontend
    template:
        metadata:
            labels:
                name: frontend
        spec:
            containers:
            - name: frontend
              image: registry.cn-hangzhou.aliyuncs.com/kubeguide/guestbook-php-frontend:latest
              env:
              - name: GET_HOSTS_FROM
                value: env
              ports:
              - containerPort: 80
