apiVersion: v1
kind: Service
metadata:
    name: frontend
    labels:
        name: frontend
spec:
    type: NodePort
    selector:
      name: frontend
    ports:
    - port: 80
      nodePort: 30001
